export default function LegalProfessional() {
    return (
        <main className="flex min-h-screen flex-col items-center justify-center text-white bg-gradient-to-b from-gray-900 to-black p-8">
            <h1 className="text-4xl font-bold">Legal & Professional Responses to Deepfakes</h1>
            <p className="mt-4 max-w-2xl text-center">
                As deepfake technology evolves, governments and IT professionals face increasing challenges in combating its misuse.
                This section explores how legal frameworks and technological solutions are being used to address the ethical,
                security, and legal threats posed by deepfakes.
            </p>

            {/* Section: Laws and Regulations on Deepfakes */}
            <div className="mt-8 max-w-3xl border-t border-gray-600 pt-6">
                <h2 className="text-2xl font-semibold">Laws and Regulations on Deepfakes</h2>
                <p className="mt-4 text-gray-300">
                    Governments worldwide are attempting to regulate deepfake technology, though legal frameworks are still evolving.
                    The main challenges include defining what constitutes harmful deepfake content, determining liability, and enforcing penalties.
                </p>

                {/* Subsection: Existing Laws and Approaches */}
                <h3 className="mt-6 text-xl font-semibold">Existing Laws and Approaches</h3>
                <p className="mt-4 text-gray-300">
                    Some countries have enacted specific laws to tackle deepfake-related crimes. For example:
                </p>
                <ul className="mt-4 text-gray-300 list-disc pl-6 space-y-2">
                    <li><b>United States:</b> Several states, including California and Texas, have laws banning malicious political and explicit deepfakes.</li>
                    <li><b>China:</b> Introduced regulations requiring deepfake content to be clearly labeled to prevent misinformation.</li>
                    <li><b>European Union:</b> Proposed the <b>Artificial Intelligence Act</b>, which includes rules on deepfake transparency.</li>
                </ul>
                <p className="mt-4 text-gray-300">
                    Despite these efforts, enforcement remains difficult. Deepfakes can be generated anonymously and distributed globally,
                    making it challenging to prosecute offenders under a single jurisdiction.
                </p>

                {/* Subsection: Legal Challenges and Enforcement Issues */}
                <h3 className="mt-6 text-xl font-semibold">Legal Challenges and Enforcement Issues</h3>
                <p className="mt-4 text-gray-300">
                    Deepfake laws must balance <b>freedom of expression and protection against harm</b>. Some key legal challenges include:
                </p>
                <ul className="mt-4 text-gray-300 list-disc pl-6 space-y-2">
                    <li><b>Proving Harm:</b> Victims must demonstrate that a deepfake has caused reputational or financial damage.</li>
                    <li><b>Jurisdictional Issues:</b> If a deepfake is created in one country but affects individuals in another, legal action becomes complex.</li>
                    <li><b>Difficulty in Identifying Creators:</b> Many deepfakes are generated by anonymous users, making prosecution difficult.</li>
                </ul>
                <p className="mt-4 text-gray-300">
                    A notable example is the <b>Bruce Willis deepfake case</b>, where a telecom company used an AI-generated version of the actor in an advertisement without direct involvement.
                    This sparked debates over whether individuals own digital versions of themselves.
                </p>
            </div>

            {/* Section: How IT Professionals Combat Deepfakes */}
            <div className="mt-8 max-w-3xl border-t border-gray-600 pt-6">
                <h2 className="text-2xl font-semibold">How IT Professionals Combat Deepfakes</h2>
                <p className="mt-4 text-gray-300">
                    As deepfake threats grow, IT professionals are developing <b>detection technologies, authentication systems, and AI-driven countermeasures</b> to mitigate their impact.
                </p>

                {/* Subsection: Deepfake Detection Technologies */}
                <h3 className="mt-6 text-xl font-semibold">Deepfake Detection Technologies</h3>
                <p className="mt-4 text-gray-300">
                    AI researchers are designing tools to detect deepfakes by analyzing inconsistencies in videos and audio. Some key techniques include:
                </p>
                <ul className="mt-4 text-gray-300 list-disc pl-6 space-y-2">
                    <li><b>Facial Analysis:</b> Detecting unnatural eye movements, blinking patterns, and inconsistencies in facial expressions.</li>
                    <li><b>Audio Detection:</b> Identifying abnormalities in speech, such as unnatural pauses or robotic inflections.</li>
                    <li><b>Metadata Verification:</b> Checking file metadata for signs of AI generation.</li>
                    <li><b>Blockchain Authentication:</b> Embedding authenticity markers in digital media to verify content legitimacy.</li>
                </ul>
                <p className="mt-4 text-gray-300">
                    Companies like Microsoft and Facebook have invested in deepfake detection tools to verify online content.
                    For instance, <b>TrueMedia’s deepfake detection tool</b> flagged a fake <b>PAGCOR news report</b> as AI-generated with 100% confidence.
                </p>

                {/* Subsection: AI and Digital Watermarking */}
                <h3 className="mt-6 text-xl font-semibold">AI and Digital Watermarking</h3>
                <p className="mt-4 text-gray-300">
                    IT experts are also using <b>digital watermarking</b> to mark authentic media, making it easier to detect altered content.
                    This involves embedding <b>invisible markers</b> within images and videos that can be verified using special software.
                </p>
                <p className="mt-4 text-gray-300">
                    <b>Google and Adobe</b> are working on AI-driven watermarking solutions to ensure that content uploaded online is traceable to its original source.
                </p>

                {/* Subsection: Cybersecurity Measures */}
                <h3 className="mt-6 text-xl font-semibold">Cybersecurity Measures</h3>
                <p className="mt-4 text-gray-300">
                    IT professionals recommend strengthening <b>cybersecurity policies</b> to prevent deepfake misuse. These include:
                </p>
                <ul className="mt-4 text-gray-300 list-disc pl-6 space-y-2">
                    <li><b>Improving Authentication Systems:</b> Using biometric verification to prevent impersonation fraud.</li>
                    <li><b>Enhancing Media Literacy:</b> Educating users on how to spot deepfake content.</li>
                    <li><b>Regulating AI Development:</b> Placing restrictions on the use of AI-generated media for deceptive purposes.</li>
                </ul>
            </div>

            {/* Section: The Future of Deepfake Regulation */}
            <div className="mt-8 max-w-3xl border-t border-gray-600 pt-6">
                <h2 className="text-2xl font-semibold">The Future of Deepfake Regulation</h2>
                <p className="mt-4 text-gray-300">
                    While current regulations are still evolving, experts predict that <b>deepfake laws will become stricter</b> as AI continues to advance.
                    Governments, tech companies, and IT professionals must collaborate to create <b>a global framework</b> that prevents misuse while allowing ethical applications of AI.
                </p>
                <p className="mt-4 text-gray-300">
                    Moving forward, <b>proactive detection technologies, digital media authentication, and stricter legislation</b> will play a crucial role in mitigating deepfake risks.
                </p>
            </div>
        </main>
    );
}
